export const Root_Routes = {
  root: "/",
  blog: "/blog",
  ourstory: "/our_story",
  case_studies: "/case_studies",
  testimonials: "/testimonials",
  seller_interactive: "/seller_interactive",
  our_team: "/our_team",
  account_management: "/account_management",
  seo: "/seo",
  ppc: "/ppc",
  product_launch: "/product_launch",
  listing_optimization: "/listing_optimization",
  protection_asistance: "/protection_asistance",
  appeal_reinstatement: "/appeal_reinstatement",
  reimbursement_refund: "/reimbursement_refund",
  wholesale_partnership_program: "/wholesale_partnership_program",
  platform_advertising: "/platform_advertising",
  contact_us: "/contact_us",
};
