export const Root_Routes = {
  root: "/",
  blog: "/blog",
  ourstory: "/our_story",
  case_studies: "/case_studies",
  testimonials: "/testimonials",
  seller_interactive: "/seller_interactive",
  our_team: "/our_team",
  account_management: "/account_management",
  amazon_seo: "/amazon_seo",
  ppc: "/ppc",
  product_launch: "/product_launch",
  listing_optimization: "/listing_optimization",
  protection_asistance: "/protection_asistance",
  appeal_reinstatement: "/appeal_reinstatement",
  reimbursement_refund: "/reimbursement_refund",
  wholesale_partnership_program: "/wholesale_partnership_program",
  platform_advertising: "/platform_advertising",
  contact_us: "/contact_us",
  gator_cable:"/gator_cable",
  hair_burst: "/hair_burst",
  quench_co: "/quench_co",
  solo_nutrition: "/solo_nutrition",
  woken_coffee: "/woken_coffee",
  tribella: "/tribella",
  gaurdian_athletic: "/gaurdian_athletic",
  vortex_enterprise: "/vortex_enterprise",
};
